"use client"

import * as React from "react"
import { Button } from "@/components/ui/button"

type Language = "en" | "fr" | "ar"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    exploreHistory: "Experience 3000 years of Tunisian history through immersive AR & VR",
    startExploring: "Start Exploring",
    "nav.home": "Home",
    "nav.explorer": "Explorer",
    "nav.figures": "Historical Figures",
    "nav.store": "Store",
    "nav.profile": "Profile",
    "store.title": "Store",
    "store.cart": "Cart",
    "store.addToCart": "Add to Cart",
    "cart.title": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.quantity": "Quantity",
    "cart.price": "Price",
    "cart.total": "Total",
    "cart.clear": "Clear Cart",
    "cart.checkout": "Checkout",
    "explorer.title": "Explore Tunisia's History",
    "explorer.startVR": "Start VR Experience",
    "explorer.gallery": "Image and Video Gallery",
    "explorer.era.Antiquity": "Antiquity",
    "explorer.era.Middle Ages": "Middle Ages",
    "explorer.era.Modern Era": "Modern Era",
    "common.BCE": "BCE",
    "common.CE": "CE",
    "figures.title": "Historical Figures",
    "figures.startConversation": "Start Conversation",
    language: "Language",
    "explorer.category.landmarks": "Landmarks",
    "explorer.category.culture": "Culture",
    "explorer.category.events": "Events",
    "profile.title": "Profile",
    "profile.subscription": "Subscription",
    "profile.premiumPlan": "Premium Plan - Valid until Dec 2024",
    "profile.statistics": "Statistics",
    "profile.timeSpent": "Time Spent",
    "profile.placesVisited": "Places Visited",
    "profile.achievements": "Achievements",
    "profile.achievement.timeTraveler": "Time Traveler",
    "profile.achievement.timeTravelerDesc": "Explored 5 different historical periods",
    "profile.achievement.historyScholar": "History Scholar",
    "profile.achievement.historyScholarDesc": "Completed 10 historical lessons",
    "profile.achievement.culturalExpert": "Cultural Expert",
    "profile.achievement.culturalExpertDesc": "Mastered 3 cultural aspects",
    "explorer.era.Ancient Carthage": "Ancient Carthage",
    "explorer.era.Roman Tunisia": "Roman Tunisia",
    "explorer.era.Modern Tunisia": "Modern Tunisia",
    "Islamic Golden Age": "Islamic Golden Age",
    "figures.name.1": "Hannibal Barca",
    "figures.name.2": "Ibn Khaldun",
    "figures.name.3": "Habib Bourguiba",
    "figures.period.1": "247-183 BCE",
    "figures.period.2": "1332-1406 CE",
    "figures.period.3": "1903-2000 CE",
    "figures.description.1": "Carthaginian general and statesman",
    "figures.description.2": "Historian and social scientist",
    "figures.description.3": "First President of Tunisia",
    "store.product1.name": "Virtual Tour: Ancient Carthage",
    "store.product1.description": "Experience the grandeur of ancient Carthage in VR",
    "store.product2.name": "Historical Tunisia Book",
    "store.product2.description": "Comprehensive guide to Tunisia's rich history",
    "store.productType.digital": "digital",
    "store.productType.physical": "physical",
    "explorer.mapAltText": "Map of Tunisia",
    "explorer.siteName.1": "Carthage",
    "explorer.siteName.2": "Kairouan",
    "explorer.siteName.3": "Medina of Tunis",
    "explorer.siteName.4": "Punic Wars",
    "explorer.siteName.5": "Arab Conquest",
    "explorer.siteName.6": "Tunisian Independence",
    "explorer.siteName.7": "Carthaginian Culture",
    "explorer.siteName.8": "Islamic Golden Age",
    "explorer.siteName.9": "Modern Tunisian Art",
    "explorer.siteDescription.1": "Ancient Phoenician and Roman city",
    "explorer.siteDescription.2": "Fourth holiest city of Islam",
    "explorer.siteDescription.3": "Historic heart of Tunis",
    "explorer.siteDescription.4": "Series of wars between Rome and Carthage",
    "explorer.siteDescription.5": "Islamic expansion into North Africa",
    "explorer.siteDescription.6": "Tunisia gains independence from France",
    "explorer.siteDescription.7": "Art, religion, and daily life in ancient Carthage",
    "explorer.siteDescription.8": "Advancements in science, art, and philosophy",
    "explorer.siteDescription.9": "Contemporary art scene in Tunisia",
    "explorer.selectSite": "Select Site",
    "explorer.nearestSite": "Nearest historical site",
    "home.feature1.text": "Traverse 3000 years of history",
    "home.feature2.text": "Explore iconic Tunisian landmarks",
    "home.feature3.text": "Immerse in rich cultural narratives",
  },
  fr: {
    exploreHistory: "Découvrez 3000 ans d'histoire tunisienne grâce à la RA et la RV immersives",
    startExploring: "Commencer l'exploration",
    "nav.home": "Accueil",
    "nav.explorer": "Explorateur",
    "nav.figures": "Personnages historiques",
    "nav.store": "Boutique",
    "nav.profile": "Profil",
    "store.title": "Boutique",
    "store.cart": "Panier",
    "store.addToCart": "Ajouter au panier",
    "cart.title": "Votre panier",
    "cart.empty": "Votre panier est vide",
    "cart.quantity": "Quantité",
    "cart.price": "Prix",
    "cart.total": "Total",
    "cart.clear": "Vider le panier",
    "cart.checkout": "Passer à la caisse",
    "explorer.title": "Explorez l'histoire de la Tunisie",
    "explorer.startVR": "Démarrer l'expérience VR",
    "explorer.gallery": "Galerie d'images et de vidéos",
    "explorer.era.Antiquity": "Antiquité",
    "explorer.era.Middle Ages": "Moyen Âge",
    "explorer.era.Modern Era": "Époque moderne",
    "common.BCE": "av. J.-C.",
    "common.CE": "apr. J.-C.",
    "figures.title": "Personnages historiques",
    "figures.startConversation": "Commencer la conversation",
    language: "Langue",
    "explorer.category.landmarks": "Monuments",
    "explorer.category.culture": "Culture",
    "explorer.category.events": "Événements",
    "profile.title": "Profil",
    "profile.subscription": "Abonnement",
    "profile.premiumPlan": "Plan Premium - Valable jusqu'en déc. 2024",
    "profile.statistics": "Statistiques",
    "profile.timeSpent": "Temps passé",
    "profile.placesVisited": "Lieux visités",
    "profile.achievements": "Réalisations",
    "profile.achievement.timeTraveler": "Voyageur temporel",
    "profile.achievement.timeTravelerDesc": "A exploré 5 périodes historiques différentes",
    "profile.achievement.historyScholar": "Érudit en histoire",
    "profile.achievement.historyScholarDesc": "A terminé 10 leçons historiques",
    "profile.achievement.culturalExpert": "Expert culturel",
    "profile.achievement.culturalExpertDesc": "A maîtrisé 3 aspects culturels",
    "explorer.era.Ancient Carthage": "Carthage antique",
    "explorer.era.Roman Tunisia": "Tunisie romaine",
    "explorer.era.Modern Tunisia": "Tunisie moderne",
    "Islamic Golden Age": "L'âge d'or islamique",
    "figures.name.1": "Hannibal Barca",
    "figures.name.2": "Ibn Khaldoun",
    "figures.name.3": "Habib Bourguiba",
    "figures.period.1": "247-183 av. J.-C.",
    "figures.period.2": "1332-1406 apr. J.-C.",
    "figures.period.3": "1903-2000 apr. J.-C.",
    "figures.description.1": "Général et homme d'État carthaginois",
    "figures.description.2": "Historien et sociologue",
    "figures.description.3": "Premier président de la Tunisie",
    "store.product1.name": "Visite virtuelle : Carthage antique",
    "store.product1.description": "Découvrez la grandeur de l'ancienne Carthage en réalité virtuelle",
    "store.product2.name": "Livre sur l'histoire de la Tunisie",
    "store.product2.description": "Guide complet de la riche histoire de la Tunisie",
    "store.productType.digital": "numérique",
    "store.productType.physical": "physique",
    "explorer.mapAltText": "Carte de la Tunisie",
    "explorer.siteName.1": "Carthage",
    "explorer.siteName.2": "Kairouan",
    "explorer.siteName.3": "Médina de Tunis",
    "explorer.siteName.4": "Guerres puniques",
    "explorer.siteName.5": "Conquête arabe",
    "explorer.siteName.6": "Indépendance tunisienne",
    "explorer.siteName.7": "Culture carthaginoise",
    "explorer.siteName.8": "Âge d'or islamique",
    "explorer.siteName.9": "Art tunisien moderne",
    "explorer.siteDescription.1": "Ancienne ville phénicienne et romaine",
    "explorer.siteDescription.2": "Quatrième ville sainte de l'Islam",
    "explorer.siteDescription.3": "Cœur historique de Tunis",
    "explorer.siteDescription.4": "Série de guerres entre Rome et Carthage",
    "explorer.siteDescription.5": "Expansion islamique en Afrique du Nord",
    "explorer.siteDescription.6": "La Tunisie obtient son indépendance de la France",
    "explorer.siteDescription.7": "Art, religion et vie quotidienne dans l'ancienne Carthage",
    "explorer.siteDescription.8": "Avancées en science, art et philosophie",
    "explorer.siteDescription.9": "Scène artistique contemporaine en Tunisie",
    "explorer.selectSite": "Sélectionner le site",
    "explorer.nearestSite": "Site historique le plus proche",
    "home.feature1.text": "Traversez 3000 ans d'histoire",
    "home.feature2.text": "Explorez les sites emblématiques tunisiens",
    "home.feature3.text": "Immergez-vous dans les récits culturels riches",
  },
  ar: {
    exploreHistory: "اختبر 3000 عام من التاريخ التونسي من خلال تقنيات الواقع المعزز والواقع الافتراضي الغامرة",
    startExploring: "ابدأ الاستكشاف",
    "nav.home": "الرئيسية",
    "nav.explorer": "المستكشف",
    "nav.figures": "شخصيات تاريخية",
    "nav.store": "المتجر",
    "nav.profile": "الملف الشخصي",
    "store.title": "المتجر",
    "store.cart": "عربة التسوق",
    "store.addToCart": "أضف إلى العربة",
    "cart.title": "عربة التسوق الخاصة بك",
    "cart.empty": "عربة التسوق فارغة",
    "cart.quantity": "الكمية",
    "cart.price": "السعر",
    "cart.total": "المجموع",
    "cart.clear": "إفراغ العربة",
    "cart.checkout": "إتمام الشراء",
    "explorer.title": "استكشف تاريخ تونس",
    "explorer.startVR": "بدء تجربة الواقع الافتراضي",
    "explorer.gallery": "معرض الصور والفيديو",
    "explorer.era.Antiquity": "العصور القديمة",
    "explorer.era.Middle Ages": "العصور الوسطى",
    "explorer.era.Modern Era": "العصر الحديث",
    "common.BCE": "قبل الميلاد",
    "common.CE": "ميلادي",
    "figures.title": "الشخصيات التاريخية",
    "figures.startConversation": "بدء المحادثة",
    language: "اللغة",
    "explorer.category.landmarks": "المعالم",
    "explorer.category.culture": "الثقافة",
    "explorer.category.events": "الأحداث",
    "profile.title": "الملف الشخصي",
    "profile.subscription": "الاشتراك",
    "profile.premiumPlan": "الخطة المميزة - صالحة حتى ديسمبر 2024",
    "profile.statistics": "الإحصائيات",
    "profile.timeSpent": "الوقت المستغرق",
    "profile.placesVisited": "الأماكن التي تمت زيارتها",
    "profile.achievements": "الإنجازات",
    "profile.achievement.timeTraveler": "مسافر عبر الزمن",
    "profile.achievement.timeTravelerDesc": "استكشف 5 فترات تاريخية مختلفة",
    "profile.achievement.historyScholar": "عالم في التاريخ",
    "profile.achievement.historyScholarDesc": "أكمل 10 دروس تاريخية",
    "profile.achievement.culturalExpert": "خبير ثقافي",
    "profile.achievement.culturalExpertDesc": "أتقن 3 جوانب ثقافية",
    "explorer.era.Ancient Carthage": "قرطاج القديمة",
    "explorer.era.Roman Tunisia": "تونس الرومانية",
    "explorer.era.Modern Tunisia": "تونس الحديثة",
    "Islamic Golden Age": "العصر الذهبي الإسلامي",
    "figures.name.1": "حنبعل برقة",
    "figures.name.2": "ابن خلدون",
    "figures.name.3": "الحبيب بورقيبة",
    "figures.period.1": "247-183 قبل الميلاد",
    "figures.period.2": "1332-1406 ميلادي",
    "figures.period.3": "1903-2000 ميلادي",
    "figures.description.1": "قائد وسياسي قرطاجي",
    "figures.description.2": "مؤرخ وعالم اجتماع",
    "figures.description.3": "أول رئيس لتونس",
    "store.product1.name": "جولة افتراضية: قرطاج القديمة",
    "store.product1.description": "اختبر عظمة قرطاج القديمة في الواقع الافتراضي",
    "store.product2.name": "كتاب تاريخ تونس",
    "store.product2.description": "دليل شامل للتاريخ الغني لتونس",
    "store.productType.digital": "رقمي",
    "store.productType.physical": "مادي",
    "explorer.mapAltText": "خريطة تونس",
    "explorer.siteName.1": "قرطاج",
    "explorer.siteName.2": "القيروان",
    "explorer.siteName.3": "مدينة تونس العتيقة",
    "explorer.siteName.4": "الحروب البونيقية",
    "explorer.siteName.5": "الفتح العربي",
    "explorer.siteName.6": "استقلال تونس",
    "explorer.siteName.7": "الثقافة القرطاجية",
    "explorer.siteName.8": "العصر الذهبي الإسلامي",
    "explorer.siteName.9": "الفن التونسي الحديث",
    "explorer.siteDescription.1": "مدينة فينيقية ورومانية قديمة",
    "explorer.siteDescription.2": "رابع أقدس مدينة في الإسلام",
    "explorer.siteDescription.3": "القلب التاريخي لتونس",
    "explorer.siteDescription.4": "سلسلة من الحروب بين روما وقرطاج",
    "explorer.siteDescription.5": "التوسع الإسلامي في شمال أفريقيا",
    "explorer.siteDescription.6": "حصول تونس على الاستقلال من فرنسا",
    "explorer.siteDescription.7": "الفن والدين والحياة اليومية في قرطاج القديمة",
    "explorer.siteDescription.8": "التقدم في العلوم والفنون والفلسفة",
    "explorer.siteDescription.9": "المشهد الفني المعاصر في تونس",
    "explorer.selectSite": "اختر الموقع",
    "explorer.nearestSite": "أقرب موقع تاريخي",
    "home.feature1.text": "عبور 3000 عام من التاريخ",
    "home.feature2.text": "استكشف المعالم التونسية الشهيرة",
    "home.feature3.text": "انغمس في الروايات الثقافية الغنية",
  },
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = React.useState<Language>("en")

  const t = React.useCallback(
    (key: string) => {
      return translations[language][key] || key
    },
    [language],
  )

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
      <LanguageSwitcher />
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = React.useContext(LanguageContext)
  if (!context) throw new Error("useLanguage must be used within LanguageProvider")
  return context
}

function LanguageSwitcher() {
  const { language, setLanguage, t } = useLanguage()

  return (
    <div className="fixed bottom-4 right-4 bg-white/10 backdrop-blur-md p-2 rounded-lg shadow-lg">
      <div className="flex items-center space-x-2">
        <span className="text-white">{t("language")}:</span>
        <Button variant={language === "en" ? "default" : "outline"} size="sm" onClick={() => setLanguage("en")}>
          EN
        </Button>
        <Button variant={language === "fr" ? "default" : "outline"} size="sm" onClick={() => setLanguage("fr")}>
          FR
        </Button>
        <Button variant={language === "ar" ? "default" : "outline"} size="sm" onClick={() => setLanguage("ar")}>
          عربي
        </Button>
      </div>
    </div>
  )
}

